// apps/web/src/lib/components/Button.svelte
<script lang="ts">
	import type { Snippet } from "svelte";

	interface Props {
		type?: "submit" | "button" | "reset";
		variant?: "primary" | "secondary" | "ghost";
		disabled?: boolean;
		class?: string;
		children: Snippet;
		onclick?: () => void;
	}

	let {
		type = "button",
		variant = "primary",
		disabled = false,
		class: extraClass = "",
		children,
		onclick,
	}: Props = $props();

	const base =
		"inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed";

	const variants = {
		primary:
			"bg-indigo-600 text-white hover:bg-indigo-700 focus:ring-indigo-500 shadow-sm",
		secondary:
			"border border-gray-300 bg-white text-gray-700 hover:bg-gray-50 focus:ring-indigo-500 shadow-sm",
		ghost: "text-gray-600 hover:text-gray-900 hover:bg-gray-100 focus:ring-indigo-500",
	};
</script>

<button {type} {disabled} {onclick} class="{base} {variants[variant]} {extraClass}">
	{@render children()}
</button>

// src/components/Button.tsx
import type React from "react";

interface ButtonProps {
	children: React.ReactNode;
	onClick?: () => void;
	variant?: "primary" | "secondary";
	disabled?: boolean;
}

export function Button({
	children,
	onClick,
	variant = "primary",
	disabled = false,
}: ButtonProps) {
	const baseStyles = "px-4 py-2 rounded font-medium transition-colors";
	const variantStyles =
		variant === "primary"
			? "bg-blue-600 text-white hover:bg-blue-700"
			: "bg-gray-200 text-gray-800 hover:bg-gray-300";
	const disabledStyles = disabled
		? "opacity-50 cursor-not-allowed"
		: "cursor-pointer";

	return (
		<button
			type="button"
			onClick={onClick}
			disabled={disabled}
			className={`${baseStyles} ${variantStyles} ${disabledStyles}`}
		>
			{children}
		</button>
	);
}
